---
#   序号    内网ip                 外网ip              端口			依赖
games:
    slots:
    - { num: 12.1, lip: '10.0.0.1', oip: '50.100.11.123', port: [ 9404, 19902 ], dep: None, GWtype: 'false' }
    match:
    - { num: 58.1, lip: '10.0.0.1', oip: '50.100.11.123', port: [ 12058, 19958 ], dep: None, GWtype: 'false' }
service:
    matchinfo:
    - { num: 18.1,  lip: '10.0.0.2', oip: '80.22.45.3', port: [ 12018, 19018 ] , dep: None, GWtype: 'false' }
    auth:
    - { num: 7.1,  lip: '10.0.0.2', oip: '80.22.45.3', port: [ 17000, 9007 ] , dep: ['corelogic','hall','oplog','statuskeeper'], GWtype: 'false' }
    cfgcenter:
    - { num: None, lip: '10.0.0.3', oip: '220.85.60.31', port: [ 15000, 16000 ] , dep: None, GWtype: 'false' }
    coredata_data:
    - { num: 6.1,  lip: '10.0.0.3', oip: '220.85.60.31', port: [ 12000, 9000 ] , dep: None, GWtype: 'false' }
    coredata_logic:
    - { num: 5.1,  lip: '10.0.0.3', oip: '220.85.60.31', port: [ 12001, 9001 ] , dep: ['coredata_data'], GWtype: 'false' }
    gamegw:
    - { num: 9.1,  lip: '10.0.0.3', oip: '220.85.60.31', port: [ 22000, 9008 ] , dep: ['jackpot','auth','corelogic','gamelist','hall','oplog','statuskeeper','toplist','matchinfo'], GWtype: 'true' }
    gamelist:
    - { num: 12.1, lip: '10.0.0.2', oip: '80.22.45.3', port: [ 12007, 9011 ] , dep: ['corelogic','oplog'], GWtype: 'false' }
    gamemaster:
    - { num: 14.1, lip: '10.0.0.3', oip: '220.85.60.31', port: [ 9320, 9321 ] , dep: ['corelogic'], GWtype: 'true' }
    gateway:
    - { num: 2.1,  lip: '10.0.0.2', oip: '80.22.45.3', port: [ 9403, 9004 ] , dep: ['jackpot','auth','hall','minigames','social','toplist','gamelist','recharge','statuskeeper','matchinfo','version'], GWtype: 'true' }
    hall:
    - { num: 4.1,  lip: '10.0.0.2', oip: '80.22.45.3', port: [ 12003, 9002 ] , dep: ['corelogic','oplog','statuskeeper','toplist'], GWtype: 'false' }
    oplogs:
    - { num: 8.1,  lip: '10.0.0.3', oip: '220.85.60.31', port: [ 12004, 9006 ] , dep: None, GWtype: 'false' }
    recharge:
    - { num: 11.1, lip: '10.0.0.2', oip: '80.22.45.3', port: [ 12006, 9010 ] , dep: ['corelogic','hall','oplog','statuskeeper','toplist'], GWtype: 'false' }
    statuskeeper:
    - { num: 15.1, lip: '10.0.0.2', oip: '80.22.45.3', port: [ 12015, 9015 ] , dep: ['corelogic','oplog'], GWtype: 'false' }
    toplist:
    - { num: 10.1, lip: '10.0.0.2', oip: '80.22.45.3', port: [ 12005, 9009 ] , dep: None, GWtype: 'false' }
    jackpot:
    - { num: 19.1,  lip: '10.0.0.2', oip: '80.22.45.3', port: [ 12019, 19019 ] , dep: ['corelogic'], GWtype: 'false' }
